"""
Generate GridPred's canonical asset registry from Formula 1's official 2026
media library.

Every driver photograph and team logo in the application resolves through the
files this writes. No component may contain an image URL.

Assets are referenced by URL from media.formula1.com and are NOT copied into
this repository. F1 publishes a per-season asset set whose path encodes the
season and the driver's current constructor, e.g.

    common/f1/2026/redbullracing/isahad01/2026redbullracingisahad01right.webp

which is why these are current where a stale cached URL would not be: a driver
who changes team gets a new path under the new team, and the mapping in
tools/f1_official_map.json is regenerated from F1's own driver index.

"""
import json, os

HERE = os.path.dirname(os.path.abspath(__file__))
DEST = os.path.join(HERE, '..', 'src', 'data')
CDN = 'https://media.formula1.com/image/upload'
VER = 'v1740000001'

mapping = json.load(open(os.path.join(HERE, 'f1_official_map.json')))
snapshot = json.load(open(os.path.join(DEST, 'snapshot', 'drivers.json')))

def driver_url(slug, code, width):
    return (f'{CDN}/c_limit,w_{width}/q_auto,f_auto/{VER}'
            f'/common/f1/2026/{slug}/{code}/2026{slug}{code}right.webp')

def team_url(slug, width=400):
    return (f'{CDN}/c_fit,w_{width},h_{width}/q_auto,f_auto/{VER}'
            f'/common/f1/2026/{slug}/2026{slug}logowhite.webp')

sources, d_entries, t_entries = [], [], []
missing = []

for d in snapshot:
    did = d['id']
    info = mapping['drivers'].get(did)
    if not info:
        missing.append(did)
        d_entries.append((did, {'code': None, 'teamSlug': None, 'source': None}))
        sources.append({'type': 'driver-headshot', 'id': did, 'source': None,
                        'licence': None,
                        'note': 'No official 2026 asset found; neutral placeholder shown.'})
        continue
    slug, code = info['slug'], info['code']
    d_entries.append((did, {'code': code, 'teamSlug': slug, 'source': 'formula1'}))
    sources.append({
        'type': 'driver-headshot', 'id': did,
        'source': 'Formula 1 official 2026 media library (media.formula1.com)',
        'assetPath': f'common/f1/2026/{slug}/{code}/2026{slug}{code}right.webp',
        'licence': 'Copyright Formula One World Championship Ltd. Referenced by URL, not redistributed.',
        'note': f'Official 2026 portrait; asset path is namespaced to {slug}, '
                f'confirming current-season team kit.',
    })

for tid, info in mapping['teams'].items():
    slug = info['slug']
    t_entries.append((tid, {'slug': slug, 'source': 'formula1'}))
    sources.append({
        'type': 'team-logo', 'id': tid,
        'source': 'Formula 1 official 2026 media library (media.formula1.com)',
        'assetPath': f'common/f1/2026/{slug}/2026{slug}logowhite.webp',
        'licence': 'Trademark of the respective constructor. Referenced by URL, not redistributed.',
        'note': 'Official 2026 white logo variant, supplied for dark backgrounds.',
    })

def js_obj(entries, indent='  '):
    out = []
    for key, val in entries:
        fields = ',\n'.join(f'{indent}  {k}: {json.dumps(v)}' for k, v in val.items())
        out.append(f'{indent}{json.dumps(key)}: {{\n{fields},\n{indent}}}')
    return ',\n'.join(out)

DRIVER_HEADER = """/**
 * GENERATED by tools/gen_assets.py — do not edit by hand.
 *
 * The single source of truth for driver imagery. No component may contain an
 * image URL; they resolve through the builders below.
 *
 * This stores the *ingredients* of a URL — F1's driver code and a fallback team
 * slug — not a frozen URL. F1 namespaces every portrait by season and
 * constructor:
 *
 *     common/f1/2026/redbullracing/isahad01/2026redbullracingisahad01right.webp
 *
 * Building the URL from a driver's CURRENT team means a mid-season move is
 * picked up automatically: the live feed reports the new constructor and the
 * portrait resolves to the new team's photograph, with no rebuild.
 */
export const F1_CDN = '{cdn}';
export const F1_ASSET_VERSION = '{ver}';
export const F1_SEASON = {season};

/** Portrait URL for a driver code under a given team slug. */
export function buildHeadshotUrl(teamSlug, code, width = 800) {{
  if (!teamSlug || !code) return null;
  return (
    `${{F1_CDN}}/c_limit,w_${{width}}/q_auto,f_auto/${{F1_ASSET_VERSION}}` +
    `/common/f1/${{F1_SEASON}}/${{teamSlug}}/${{code}}/${{F1_SEASON}}${{teamSlug}}${{code}}right.webp`
  );
}}

/** Responsive srcset for the same portrait. */
export function buildHeadshotSrcSet(teamSlug, code) {{
  if (!teamSlug || !code) return null;
  return [400, 800, 1200]
    .map((w) => `${{buildHeadshotUrl(teamSlug, code, w)}} ${{w}}w`)
    .join(', ');
}}

/**
 * F1 derives a driver code from the first three letters of each name. That
 * holds across the current grid except for drivers who race under a shortened
 * given name, so a known code always wins over a derived one.
 */
export function deriveDriverCode(firstName, lastName) {{
  const clean = (s) =>
    String(s ?? '')
      .normalize('NFD')
      .replace(/[\u0300-\u036f]/g, '')
      .toLowerCase()
      .replace(/[^a-z]/g, '');
  const f = clean(firstName).slice(0, 3);
  const l = clean(lastName).slice(0, 3);
  return f.length === 3 && l.length === 3 ? `${{f}}${{l}}01` : null;
}}

""".format(cdn=CDN, ver=VER, season=2026)

open(os.path.join(DEST, 'driverAssets.js'), 'w').write(
    DRIVER_HEADER + 'export const driverAssets = {\n' + js_obj(d_entries) + ',\n};\n\n'
    'export const getDriverAsset = (id) =>\n'
    "  driverAssets[id] ?? { code: null, teamSlug: null, source: null };\n")

TEAM_HEADER = """/**
 * GENERATED by tools/gen_assets.py — do not edit by hand.
 *
 * Team logo registry. Formula 1's official 2026 white logo variants, referenced
 * from media.formula1.com and not copied into this repository. Trademarks
 * remain those of the respective constructors and are used nominatively to
 * identify the team.
 *
 * Stores the team slug rather than a URL so a logo resolves the same way a
 * portrait does, and a team with no entry — or a logo that fails to load —
 * renders a neutral GridPred plate carrying the team's own name and colour,
 * never another team's logo.
 */
import { F1_CDN, F1_ASSET_VERSION, F1_SEASON } from './driverAssets';

/** Logo URL for a team slug. */
export function buildTeamLogoUrl(slug, width = 400) {
  if (!slug) return null;
  return (
    `${F1_CDN}/c_fit,w_${width},h_${width}/q_auto,f_auto/${F1_ASSET_VERSION}` +
    `/common/f1/${F1_SEASON}/${slug}/${F1_SEASON}${slug}logowhite.webp`
  );
}

"""

open(os.path.join(DEST, 'teamAssets.js'), 'w').write(
    TEAM_HEADER + 'export const teamAssets = {\n' + js_obj(t_entries) + ',\n};\n\n'
    "export const getTeamAsset = (id) => teamAssets[id] ?? { slug: null, source: null };\n\n"
    'export const getTeamLogo = (id, width) => buildTeamLogoUrl(teamAssets[id]?.slug, width);\n')

open(os.path.join(DEST, 'assetSources.js'), 'w').write(
    """/**
 * GENERATED by tools/gen_assets.py — do not edit by hand.
 *
 * Provenance and licensing for every externally referenced asset. Development
 * documentation; surfaced to users only on the /assets-debug page.
 *
 * All imagery is referenced by URL from Formula 1's official media library and
 * is not redistributed in this repository. Confirm you hold the rights you need
 * for your own deployment context.
 */
export const assetSources = """ + json.dumps(sources, indent=1, ensure_ascii=False) + ';\n\n'
    'export const sourcesFor = (id) => assetSources.filter((s) => s.id === id);\n')

print(f'  driverAssets.js  {len(d_entries)} drivers ({len(d_entries)-len(missing)} official, {len(missing)} missing)')
print(f'  teamAssets.js    {len(t_entries)} official logos')
print(f'  assetSources.js  {len(sources)} records')
if missing: print('  MISSING:', missing)
